silence:
  threshold_db: -34
  min_keep_duration: 0.4
  buffer_before: 0.2
  buffer_after: 0.3
broll:
  matching_threshold: 0.65
  max_overlay_duration: 3.0
  fit_mode: center
  crossfade: 0.3
  cooldown_sec: 30
query:
  top_n_tokens: 6
vision:
  max_frames: 12
  base_frames: 6
resolve:
  timeline_name_prefix: "VideoForge_"
